#!/usr/bin/env bash
#cloud-config

users:
  - name: {{ user }}
    ssh_authorized_keys:
      - {{ public_key }}
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    groups: sudo
    shell: /bin/bash

    
# fix bug with missing hostname keys
dpkg-reconfigure openssh-server

systemctl restart sshd


# fix networking bug
tee /etc/network/interfaces <<EOF
# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

source /etc/network/interfaces.d/*

# The loopback network interface
auto lo
iface lo inet loopback

# The primary network interface
allow-hotplug enp1s0
iface enp1s0 inet dhcp

EOF

systemctl restart networking


