#cloud-config
hostname: {{ vm_name }}
users:
  - name: {{ user }}
    ssh_authorized_keys:
      - {{ public_key }}
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    lock_passwd: true
    groups: sudo
    shell: /bin/bash

ssh_pwauth: false
chpasswd:
  expire: false
  users:
    - name: {{ user }}
      password: password1
      type: text

